# Generated by Django 5.2.14 on 2026-06-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_applicantprofile_resume_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='is_open_to_opportunities',
            field=models.BooleanField(default=True),
        ),
    ]
