# Generated by Django 5.2.14 on 2026-07-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_applicantprofile_is_open_to_opportunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills_used',
            field=models.ManyToManyField(blank=True, help_text='Skills actually used in this role ', related_name='used_in_experiences', to='users.skill'),
        ),
    ]
