# Generated by Django 5.2.14 on 2026-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_experience_skills_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_level',
            field=models.CharField(blank=True, choices=[('below_matric', 'Below Matric'), ('matric', 'Matric / SSC'), ('o_level', 'O-Level'), ('intermediate', 'Intermediate / FSc / FA / ICS'), ('a_level', 'A-Level'), ('hssc', 'HSSC'), ('diploma', 'Diploma / DAE'), ('hnd', 'HND (Higher National Diploma)'), ('associate', "Associate's Degree"), ('bachelors', "Bachelor's (BA/BSc/BBA/BCom/etc.)"), ('bachelors_hons', "Bachelor's Honours (4-year BS)"), ('llb', 'LLB'), ('masters', "Master's (MA/MSc/MBA/MCom/etc.)"), ('llm', 'LLM'), ('mphil', 'MPhil'), ('mbbs', 'MBBS'), ('jd', 'JD (Juris Doctor)'), ('pharmd', 'PharmD'), ('phd', 'PhD / Doctorate'), ('postdoc', 'Post-Doctoral')], help_text='Explicit level selected by the user — used for education-tier matching instead of parsing free text.', max_length=30, null=True),
        ),
    ]
