# Generated by Django 5.2.14 on 2026-08-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_education_degree_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_level',
            field=models.CharField(choices=[('below_matric', 'Below Matric'), ('matric', 'Matric / SSC'), ('o_level', 'O-Level'), ('intermediate', 'Intermediate / FSc / FA / ICS'), ('a_level', 'A-Level'), ('hssc', 'HSSC'), ('diploma', 'Diploma / DAE'), ('hnd', 'HND (Higher National Diploma)'), ('associate', "Associate's Degree"), ('bachelors', "Bachelor's (BA/BSc/BBA/BCom/etc.)"), ('bachelors_hons', "Bachelor's Honours (4-year BS)"), ('llb', 'LLB'), ('masters', "Master's (MA/MSc/MBA/MCom/etc.)"), ('llm', 'LLM'), ('mphil', 'MPhil'), ('mbbs', 'MBBS'), ('jd', 'JD (Juris Doctor)'), ('pharmd', 'PharmD'), ('phd', 'PhD / Doctorate'), ('postdoc', 'Post-Doctoral')], default='matric', max_length=30),
            preserve_default=False,
        ),
    ]
