# Generated by Django 5.2.14 on 2026-08-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_education_degree_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='skills_used',
            field=models.ManyToManyField(help_text='Skills actually used in this role', related_name='used_in_experiences', to='users.skill'),
        ),
    ]
