# Generated by Django 5.2.14 on 2026-08-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_experience_skills_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='skills_used',
            field=models.ManyToManyField(related_name='used_in_experiences', to='users.skill'),
        ),
    ]
