# Generated by Django 5.2.14 on 2026-06-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='users.applicantprofile'),
        ),
        migrations.AddField(
            model_name='interviewinvite',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='users.applicantprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.companyprofile'),
        ),
        migrations.AddField(
            model_name='interviewinvite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='compatibility',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', through='jobs.JobSkill', to='users.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewinvite',
            unique_together={('job', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='compatibility',
            unique_together={('user', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill')},
        ),
    ]
