# Generated by Django 5.2.14 on 2026-06-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvite',
            name='candidate_response',
            field=models.TextField(blank=True),
        ),
    ]
