# Generated by Django 5.2.14 on 2026-06-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_interviewinvite_candidate_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cached_title_vec',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
