# Generated by Django 5.2.14 on 2026-07-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_cached_title_vec'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_credential',
            field=models.CharField(blank=True, help_text='Regulated credential code required for this role, e.g. MBBS, CA, BAR, PE. Leave blank for non-regulated roles.', max_length=20, null=True),
        ),
    ]
