# Generated by Django 5.2.14 on 2026-07-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_required_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibility',
            name='exceeds_experience',
            field=models.BooleanField(default=False),
        ),
    ]
