# Generated by Django 5.2.14 on 2026-08-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_required_degree_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cached_edu_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
