# Generated by Django 5.2.14 on 2026-08-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_cached_edu_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accept_related_education_fields',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_degree_level',
            field=models.CharField(blank=True, choices=[('below_matric', 'Below Matric'), ('matric', 'Matric / SSC'), ('o_level', 'O-Level'), ('intermediate', 'Intermediate / FSc / FA / ICS'), ('a_level', 'A-Level'), ('hssc', 'HSSC'), ('diploma', 'Diploma / DAE'), ('hnd', 'HND (Higher National Diploma)'), ('associate', "Associate's Degree"), ('bachelors', "Bachelor's (BA/BSc/BBA/BCom/etc.)"), ('bachelors_hons', "Bachelor's Honours (4-year BS)"), ('llb', 'LLB'), ('masters', "Master's (MA/MSc/MBA/MCom/etc.)"), ('llm', 'LLM'), ('mphil', 'MPhil'), ('mbbs', 'MBBS'), ('jd', 'JD (Juris Doctor)'), ('pharmd', 'PharmD'), ('phd', 'PhD / Doctorate'), ('postdoc', 'Post-Doctoral')], max_length=30, null=True),
        ),
    ]
