# Generated by Django 5.2.14 on 2026-08-02 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_accept_related_education_fields_and_more'),
        ('users', '0007_alter_experience_skills_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.applicantprofile')),
                ('compatibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='jobs.compatibility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillMatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_skill_text', models.CharField(max_length=150)),
                ('user_skill_text', models.CharField(max_length=150)),
                ('judged_same', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TitleMatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('experience_role', 'Experience Role'), ('education_field', 'Education Field')], max_length=20)),
                ('job_text', models.CharField(max_length=200)),
                ('user_text', models.CharField(max_length=200)),
                ('judged_same', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillDistinctOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_a_norm', models.CharField(db_index=True, max_length=150)),
                ('skill_b_norm', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.skillmatchfeedback')),
            ],
            options={
                'unique_together': {('skill_a_norm', 'skill_b_norm')},
            },
        ),
        migrations.CreateModel(
            name='SkillAliasOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_a_norm', models.CharField(db_index=True, max_length=150)),
                ('skill_b_norm', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.skillmatchfeedback')),
            ],
            options={
                'unique_together': {('skill_a_norm', 'skill_b_norm')},
            },
        ),
        migrations.CreateModel(
            name='TitleMatchOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('experience_role', 'Experience Role'), ('education_field', 'Education Field')], max_length=20)),
                ('text_a_norm', models.CharField(db_index=True, max_length=200)),
                ('text_b_norm', models.CharField(db_index=True, max_length=200)),
                ('judged_same', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.titlematchfeedback')),
            ],
            options={
                'unique_together': {('kind', 'text_a_norm', 'text_b_norm')},
            },
        ),
    ]
