# Generated by Django 5.2.14 on 2026-08-03 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_matchflag_skillmatchfeedback_titlematchfeedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_credential',
        ),
    ]
