# Generated by Django 5.2.14 on 2026-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_required_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibility',
            name='matched_education_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compatibility',
            name='relevant_experience_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
