# Generated by Django 5.2.14 on 2026-08-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_compatibility_matched_education_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibility',
            name='matched_skill_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
